blog_ejemplo/api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views
from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet
from rest_framework.authtoken import views as views_token

router = routers.DefaultRouter()
router.register('usuarios', views.UserViewSet)
router.register('perfil_usuario', views.PefilUsuarioViewSet)
router.register('posts', views.PostViewSet)

router.register('devices', FCMDeviceAuthorizedViewSet)


'localhost:8000/api/'
'localhost:8000/api/usuarios'
'localhost:8000/api/perfil_usuario'
'localhost:8000/api/posts'

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    
    path('api-token-auth/', views_token.obtain_auth_token)
]
    

blog_ejemplo/blog/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('detalle/<int:pk>', views.PostDetailView.as_view(), name='detalle'),
    path('crear', views.post_crear, name='crear'),
]

blog_ejemplo/blog_ejemplo/urls.py
from django.contrib import admin
from django.urls import path, include
#Se necesitan para obtener las imagenes en desarrollo
from django.conf.urls.static import static
from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuario/', include('gestion_usuarios.urls')),
    path('', include('blog.urls')),
    path('api/', include('api.urls')),
    path('', include('cloud_messaging.urls')),
    url('', include('pwa.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#Se incluye esta linea para poder acceder a las imagenes del trabajo

blog_ejemplo/blog/models.py
from django.db import models
from django.utils import timezone
from fcm_django.models import FCMDevice

# Create your models here.

class Post(models.Model):
    autor = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    titulo = models.CharField(max_length=200)
    contenido = models.TextField()
    fecha_creacion = models.DateTimeField(default=timezone.now)
    fecha_publicacion = models.DateTimeField(blank=True, null=True)
    imagen = models.FileField(blank=True, null=True, upload_to="blog")


    def publish(self):
        self.fecha_publicacion = timezone.now()
        devices = FCMDevice.objects.all()
        devices.send_message(title="Prueba", body="Cuerpo", data={"test": "test"})
        self.save()

    def __str__(self):
        return self.titulo

blog_ejemplo/blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Post

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('titulo', 'contenido', 'imagen', 'fecha_publicacion','autor')
        widgets={ 
            'fecha_publicacion': forms.DateInput(attrs={'type':'date'}), 
            'autor':forms.HiddenInput()
            }


    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})
        ##Otro ejemplo
        #self.fields['autor']=forms.ModelChoiceField(queryset=User.objects.all(), widget=)
        

blog_ejemplo/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Post
from django.utils import timezone
from django.urls import reverse
from .forms import PostForm
from django.views.generic import DetailView, ListView
# Create your views here.


class PostListView(ListView):
    model = Post
    template_name = "blog/index.html"


def post_lista(request):
    posts = None
    if request.user.is_authenticated:
        posts = Post.objects.all().order_by('fecha_publicacion')
    else:
        posts = Post.objects.filter(
            fecha_publicacion__lte=timezone.now()).order_by('fecha_publicacion')
    error = None
    if 'error' in request.session:
        error = request.session['error']
        del request.session['error']

    return render(request, 'blog/index.html', {'posts': posts, 'error': error})


def post_crear(request):
    if not request.user.is_authenticated:
        request.session['error'] = "Sin autorización para agregar nuevos post"
        return render(request, 'gestion_usuarios/login.html', {})

    if request.method == 'GET':
        post_form = PostForm(initial={'autor': request.user.pk})
        return render(request, 'blog/post_crear.html', {'post_form': post_form})
    elif request.method == 'POST':
        message = ""
        try:
            post_form = PostForm(data=request.POST)
            if post_form.is_valid():
                # post.fecha_publicacion = lambda fecha_publicacion : None if fecha_publicacion == "" else request.POST.get('fecha_publicacion')
                post = post_form.save()
                file = request.FILES['imagen']
                ext = file.name.split(".")[-1]
                file.name = str(post.pk) + "." + ext
                post.imagen = file
                post.save()
                message = "Éxito al guardar la publicación"
                return HttpResponseRedirect(reverse('blog:detalle', args=(post.pk,)))
            else:
                message = post_form.errors
                return render(request, 'blog/post_crear.html', {'message': message, 'post_form': post_form})
        except Exception as e:
            message = "Error al guardar la publicación: " + str(e)
            return render(request, 'blog/post_crear.html', {'message': message})
    else:
        response = HttpResponse('Método no permitido')
        response.status_code = 405
        return response


class PostDetailView(DetailView):
    model = Post
    template_name = "blog/post_detalle.html"

    #def get_context_data(self, **kwargs):
    #    context = super(PostDetailView, self).get_context_data(**kwargs)
    #    context['form'] = PostForm
    #    return context
#
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = super(PostDetailView, self).get_context_data(**kwargs)
        print(self.object.pk)
        post = get_object_or_404(Post, pk=self.object.pk)
        post.publish()
        return self.render_to_response( context=context)
    


def post_detalle(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        post.publish()
    try:
        return render(request, 'blog/post_detalle.html', {'post': post})
    except Exception as e:
        response = HttpResponse("Error al guardar la publicación: " + str(e))
        response.status_code = 404
        return response

blog_ejemplo/blog/templates/blog/index.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<script src="{% static 'blog/index.js' %}"></script>
{% endblock head %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <h1>Bienvenido al blog</h1>
  </div>
</div>

<div id="lista_posts" class="container row">
  <article class="col-12 col-md-4 col-lg-3">
    <article class="card">
      <div class="card-img-top loading">
        <div class="d-flex justify-content-center">
          <div class="spinner-border m-5 text-info" role="status">
            <span class="sr-only">Loading...</span>
          </div>
        </div>
      </div>
      <div class="card-body">
        <h5 class="card-title loading">
          <div class="spinner-grow spinner-grow-sm text-primary" role="status">
            <span class="sr-only">Loading...</span>
          </div>
          <div class="spinner-grow spinner-grow-sm text-primary" role="status">
            <span class="sr-only">Loading...</span>
          </div>
          <div class="spinner-grow spinner-grow-sm text-primary" role="status">
            <span class="sr-only">Loading...</span>
          </div>
        </h5>
        <p class="card-text">
          <div class="d-flex justify-content-center">
            <div class="spinner-border m-5" role="status">
              <span class="sr-only">Loading...</span>
            </div>
          </div>
        </p>
      </div>
      <div class="card-footer text-muted">
        --
      </div>
    </article>
  </article>

  <article class="col-12 col-md-4 col-lg-3">
    <article class="card">
      <div class="card-img-top loading">
        <div class="d-flex justify-content-center">
          <div class="spinner-border m-5 text-info" role="status">
            <span class="sr-only">Loading...</span>
          </div>
        </div>
      </div>
      <div class="card-body">
        <h5 class="card-title loading">
          <div class="spinner-grow spinner-grow-sm text-primary" role="status">
            <span class="sr-only">Loading...</span>
          </div>
          <div class="spinner-grow spinner-grow-sm text-primary" role="status">
            <span class="sr-only">Loading...</span>
          </div>
          <div class="spinner-grow spinner-grow-sm text-primary" role="status">
            <span class="sr-only">Loading...</span>
          </div>
        </h5>
        <p class="card-text">
          <div class="d-flex justify-content-center">
            <div class="spinner-border m-5" role="status">
              <span class="sr-only">Loading...</span>
            </div>
          </div>
        </p>
      </div>
      <div class="card-footer text-muted">
        --
      </div>
    </article>
  </article>
  <article class="col-12 col-md-4 col-lg-3">
    <article class="card">
      <div class="card-img-top loading">
        <div class="d-flex justify-content-center">
          <div class="spinner-border m-5 text-info" role="status">
            <span class="sr-only">Loading...</span>
          </div>
        </div>
      </div>
      <div class="card-body">
        <h5 class="card-title loading">
          <div class="spinner-grow spinner-grow-sm text-primary" role="status">
            <span class="sr-only">Loading...</span>
          </div>
          <div class="spinner-grow spinner-grow-sm text-primary" role="status">
            <span class="sr-only">Loading...</span>
          </div>
          <div class="spinner-grow spinner-grow-sm text-primary" role="status">
            <span class="sr-only">Loading...</span>
          </div>
        </h5>
        <p class="card-text">
          <div class="d-flex justify-content-center">
            <div class="spinner-border m-5" role="status">
              <span class="sr-only">Loading...</span>
            </div>
          </div>
        </p>
      </div>
      <div class="card-footer text-muted">
        --
      </div>
    </article>
  </article>


</div>

{% endblock content %}

blog_ejemplo/blog/templates/blog/post_crear.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<script>
    $(function () {
        console.log($("#formCrearPost")[0].elements.csrfmiddlewaretoken.value);
        $("#formCrearPost").on("submit", function (evt) {
            evt.preventDefault();
            //Al crear un evento sobre un elemento, la variable this es el elemento completo
            //Por lo tanto, utilizamos this para obtener los input
            //Otra forma es hacerlo con jquery a travé de los ID que se generan con el mismo formulario por ejemplo:
            //console.log(new Date($("#id_fecha_publicacion").val()).toISOString());
            let fecha_publicacion = $("#id_fecha_publicacion").val();
            let data = {
                csrfmiddlewaretoken: getCookie("csrftoken"),
                //csrf_token : getCookie('csrftoken'),
                autor: this.elements.id_autor.value,
                titulo: this.elements.id_titulo.value,
                contenido: $("#id_contenido").val(),
                fecha_publicacion: fecha_publicacion ? new Date(fecha_publicacion).toISOString() : null

            };
            $.ajax({
                    url: "/api/posts/",
                    type: "post",
                    data: data
                })
                .done(function (response) {
                    alert("guardado")
                    console.log(response);
                })
                .fail(function (error) {
                    alert("error")
                    console.log("error", error);
                });
        });
    });
</script>
{% endblock head %} {% block content %}

<a href="{% url 'blog:index' %}">Volver a la lista</a>
<div>
    {{ message }}
</div>
<br />
<form id="formCrearPost" enctype="multipart/form-data">
    {% csrf_token %}
    <label>
        Autor
    </label>
    {{ request.user.username }} {{ post_form.as_p }}

    <button type="submit" class="btn btn-primary" id="submitbutton">Crear post</button>
</form>

{% endblock content %}

blog_ejemplo/blog/templates/blog/post_detalle.html
{% extends "base.html" %}
{% load tz %}
{% block content %}

<a href="{% url 'blog:index' %}">Volver a la lista</a>

{% if post.fecha_publicacion == None %}
<form method="POST" action="{% url 'blog:detalle' post.pk %}">
    {% csrf_token %}
    <input type="hidden" value="{{post.pk}}">
    <input type="submit" value="Publicar">
</form>
{% endif %}
<div style="margin:0 auto">
    <h1 style="text-align:center"><a href="{% url 'blog:detalle' post.pk %}">{{ post.titulo }}</a></h1>
    <hr>
    <p>Publicado: {{ post.fecha_publicacion }}</p>
    <p>Autor: {{ post.autor }}</p>
    <hr>
    <p style="text-align:center"><img src="/media/{{ post.imagen }}" style="max-width:500px;"></p>
    <p>{{ post.contenido|linebreaksbr }}</p>
</div>


{% endblock content %}