blog_ejemplo/api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views
from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet
from rest_framework.authtoken import views as views_token

router = routers.DefaultRouter()
router.register('usuarios', views.UserViewSet)
router.register('perfil_usuario', views.PefilUsuarioViewSet)
router.register('posts', views.PostViewSet)

router.register('devices', FCMDeviceAuthorizedViewSet)


'localhost:8000/api/'
'localhost:8000/api/usuarios'
'localhost:8000/api/perfil_usuario'
'localhost:8000/api/posts'

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    
    path('api-token-auth/', views_token.obtain_auth_token)
]
    

blog_ejemplo/blog/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('detalle/<int:pk>', views.PostDetailView.as_view(), name='detalle'),
    path('crear', views.post_crear, name='crear'),
]

blog_ejemplo/blog_ejemplo/urls.py
from django.contrib import admin
from django.urls import path, include
#Se necesitan para obtener las imagenes en desarrollo
from django.conf.urls.static import static
from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuario/', include('gestion_usuarios.urls')),
    path('', include('blog.urls')),
    path('api/', include('api.urls')),
    path('', include('cloud_messaging.urls')),
    url('', include('pwa.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#Se incluye esta linea para poder acceder a las imagenes del trabajo

blog_ejemplo/gestion_usuarios/urls.py
from django.conf.urls import url
from . import views
app_name = 'gestion_usuarios'

urlpatterns = [
    url('registrar/', views.registrar, name='registrar'),
    url('login/', views.usuario_login, name='login'),
    url('logout/', views.usuario_logout, name='logout'),
]

blog_ejemplo/templates/base.html
{% load static %}
{% load pwa %}
<!DOCTYPE html>
<html>

<head>
    <script src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/estilo.css' %}" rel="stylesheet">
    {% progressive_web_app_meta %}
    <!-- The core Firebase JS SDK is always required and must be listed first -->
    <script src="https://www.gstatic.com/firebasejs/8.2.1/firebase-app.js"></script>

    <!-- TODO: Add SDKs for Firebase products that you want to use
     https://firebase.google.com/docs/web/setup#available-libraries -->
    <script src="https://www.gstatic.com/firebasejs/7.23.0/firebase-messaging.js"></script>

    <script>
        // Your web app's Firebase configuration
    </script>

    <script src="{% static 'js/messaging.js' %}"></script>
    {% block head %}
    {% endblock %}
</head>

<body>

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Ejemplo</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarAccesos"
                aria-controls="navbarAccesos" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarAccesos">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"><a class="nav-link" href="{% url 'blog:index' %}">index</a></li>
                    {% if not request.user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'gestion_usuarios:login' %}">iniciar
                            sesión</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'gestion_usuarios:registrar' %}">registrar</a>
                    </li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'blog:crear' %}">crear post</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'gestion_usuarios:logout' %}">logout</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>